name: Java CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: JDK 1.11 Install
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Build
        run: |
          mvn -B clean package
          mkdir staging
          cp target/*.jar staging

      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      - name: Make Release
          uses: softprops/action-gh-release@v0.1.5
          with:
          files:
            target/*.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
